Updated

diff --git a/installit b/installit
--- a/installit
+++ b/installit
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - installit
 # Started On        - Thu 14 Sep 14:44:27 BST 2017
-# Last Change       - Mon 18 Sep 17:17:27 BST 2017
+# Last Change       - Thu  5 Oct 18:33:29 BST 2017
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -11,24 +11,23 @@
 XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
 ERR(){ echo "ERROR: $1" 1>&2; }
 
-DEPCOUNT=0
-for DEP in /usr/bin/wget /bin/{rm,chmod,chown,cat,mkdir}
-{
-	if ! type -P "$DEP" &> /dev/null
-	then
-		ERR "Dependency '$DEP' not met."
-		let DEPCOUNT++
-	fi
+declare -i DEPCOUNT=0
+for DEP in /usr/bin/wget /bin/{rm,chmod,chown,mkdir}; {
+	[ -x "$DEP" ] || {
+		ERR "$LINENO" "Dependency '$DEP' not met."
+		DEPCOUNT+=1
+	}
 }
 
 [ $DEPCOUNT -eq 0 ] || exit 1
 
 shopt -s extglob
 
-USAGE()
-{
-	/bin/cat <<-EOF
-		            INSTALLIT (18th September 2017)
+USAGE(){
+	while read -r; do
+		echo "$REPLY"
+	done <<-EOF
+		            INSTALLIT (5th October 2017)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 		
 		            Installer for many shell programs from terminalforlife.
@@ -52,8 +51,7 @@ USAGE()
 	EOF
 }
 
-for ARG in $@
-{
+for ARG in $@; {
 	case "$ARG"
 	in
 		--help|-h|-\?)
@@ -67,14 +65,14 @@ for ARG in $@
 		--uninstall|-u)
 			UNINSTALL="true" ;;
 		*)
-			XERR "Incorrect argument(s) specified." ;;
+			XERR "$LINENO" "Incorrect argument(s) specified." ;;
 	esac
 }
 
 # [N]ormal [V]er[b]osity
 NVB(){ printf "L%-0.3d: %s\n" "$1" "$2"; }
 
-[ $UID -eq 0 ] || XERR "Root access is required."
+[ $UID -eq 0 ] || XERR "$LINENO" "Root access is required."
 
 [ "$BEQUIET" == "true" ] && exec 1> /dev/null
 [ "$DEBUGME" == "true" ] && set -xeu
@@ -82,10 +80,7 @@ NVB(){ printf "L%-0.3d: %s\n" "$1" "$2"; }
 GITHUB_URL="https://raw.githubusercontent.com/terminalforlife"
 PROJECT=""
 
-if [ "$UNINSTALL" == "true" ]
-then
-	NVB "$LINENO" "Uninstalling program."
-fi
+[ "$UNINSTALL" == "true" ] && NVB "$LINENO" "Uninstalling program."
 
 for FILENAME in\
 \
@@ -98,7 +93,7 @@ for FILENAME in\
 		then
 			if ! [ "$FORCE_INSTALL" == "true" ]
 			then
-				ERR "Conflict found: ${FILENAME%:*}"
+				ERR "$LINENO" "Conflict found: ${FILENAME%:*}"
 				continue
 			else
 				NVB "$LINENO" "Item updated: ${FILENAME%:*}"
@@ -118,13 +113,13 @@ for FILENAME in\
 			NVB "$LINENO" "Sending to trash: ${FILENAME%:*}"
 			if ! /usr/bin/gvfs-trash "${FILENAME%:*}" &> /dev/null
 			then
-				ERR "Failed to trash: ${FILENAME%:*}"
+				ERR "$LINENO" "Failed to trash: ${FILENAME%:*}"
 			fi
 		else
 			NVB "$LINENO" "Deleting: ${FILENAME%:*}"
 			if /bin/rm -i "${FILENAME%:*}" &> /dev/null
 			then
-				ERR "Failed to delete: ${FILENAME%:*}"
+				ERR "$LINENO" "Failed to delete: ${FILENAME%:*}"
 			fi
 		fi
 	fi
